const fs = require('fs');
const path = require('path');
const { v4: uuidv4 } = require('uuid');
const appConfig = require('../config/app.config');
const { FOLDERS } = require('../constants/file');
const ensureDir = (dir) => { if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true }); };
const ensureUploadDirs = () => Object.values(FOLDERS).forEach((f) => ensureDir(path.join(appConfig.uploadDir, f)));
const buildFileName = (ext = '.jpg') => `${Date.now()}-${uuidv4()}${ext}`;
const relativeUploadPath = (folder, fileName) => `/uploads/${folder}/${fileName}`;
const absoluteUploadPath = (folder, fileName) => path.join(appConfig.uploadDir, folder, fileName);
module.exports = { ensureDir, ensureUploadDirs, buildFileName, relativeUploadPath, absoluteUploadPath };
