const sequelize = require('../config/db');
const User = require('./user.model');
const SceneTemplate = require('./scene-template.model');
const Image = require('./image.model');
const ImageTask = require('./image-task.model');
const ImageResult = require('./image-result.model');
const Order = require('./order.model');
const PaymentRecord = require('./payment-record.model');
const DownloadRecord = require('./download-record.model');
const AdminUser = require('./admin-user.model');
User.hasMany(Image, { foreignKey: 'user_id' });
Image.belongsTo(User, { foreignKey: 'user_id' });
Image.hasMany(ImageTask, { foreignKey: 'image_id' });
ImageTask.belongsTo(Image, { foreignKey: 'image_id' });
Image.hasMany(ImageResult, { foreignKey: 'image_id' });
ImageResult.belongsTo(Image, { foreignKey: 'image_id' });
ImageTask.hasOne(ImageResult, { foreignKey: 'task_id' });
ImageResult.belongsTo(ImageTask, { foreignKey: 'task_id' });
Order.belongsTo(User, { foreignKey: 'user_id' });
Order.belongsTo(Image, { foreignKey: 'image_id' });
Order.belongsTo(ImageResult, { foreignKey: 'result_id' });
PaymentRecord.belongsTo(Order, { foreignKey: 'order_id' });
module.exports = { sequelize, User, SceneTemplate, Image, ImageTask, ImageResult, Order, PaymentRecord, DownloadRecord, AdminUser };
