ALTER TABLE photo_tasks
  MODIFY COLUMN status ENUM('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'TIMEOUT') NOT NULL DEFAULT 'PENDING',
  ADD COLUMN stage_code VARCHAR(32) NOT NULL DEFAULT 'received' AFTER status,
  ADD COLUMN stage_text VARCHAR(64) NOT NULL DEFAULT '已接收照片' AFTER stage_code,
  ADD COLUMN progress INT UNSIGNED NOT NULL DEFAULT 0 AFTER stage_text;
